src/Entity/Team.php
<?php

namespace App\Entity;

use App\Model\Event\Tournament\Action\GroupStage;
use App\Repository\TeamRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TeamRepository::class)]
class Team
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToOne(cascade: ['persist', 'remove'], inversedBy: 'teams')]
    private ?Division $division = null;

    /**
     * @var Collection<int, Result>
     */
    #[ORM\OneToMany(targetEntity: Result::class, mappedBy: 'Team', cascade: ['persist', 'remove'])]
    private Collection $results;

    public function __construct()
    {
        $this->results = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDivision(): ?Division
    {
        return $this->division;
    }

    public function setDivision(?Division $division): static
    {
        $this->division = $division;

        return $this;
    }

    /**
     * @return Collection<int, Result>
     */
    public function getResults(): Collection
    {
        return $this->results;
    }

    /**
     * @return Collection<int, Result>
     */
    public function getGroupResults(): Collection
    {
        return $this->results->filter(function ($result) {
            return $result->getStage() === GroupStage::STAGE;
        });
    }

    /**
     * @return Collection<int, Result>
     */
    public function getPlayoffResults(): Collection
    {
        return $this->results->filter(function ($result) {
            return $result->getStage() !== GroupStage::STAGE;
        });
    }

    public function addResult(Result $result): static
    {
        if (!$this->results->contains($result)) {
            $this->results->add($result);
            $result->setTeam($this);
        }

        return $this;
    }

    public function removeResult(Result $result): static
    {
        if ($this->results->removeElement($result)) {
            // set the owning side to null (unless already changed)
            if ($result->getTeam() === $this) {
                $result->setTeam(null);
            }
        }

        return $this;
    }

    public function getWinsQuantity(): int
    {
        return $this->getGroupResults()->filter(function ($element) {
            /** @var Result $element */
            return $this->getId() === $element->getWinnerId();
        })->count();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
    {% block stylesheets %}
    {% endblock %}

    {% block javascripts %}
        <script type='text/javascript' src='http://code.jquery.com/jquery-latest.js'></script>
    {% endblock %}
    <style>
        table {border-collapse: collapse;display: inline-block;padding-left: 20px;}
        td, th, caption {border: 2px solid #ddd;padding: 3px 3px;text-align: center;}
        th {background: #f7f7f7;}
        .split {float:left; display:flex;width: 42%;}
        .round {float:left; flex-direction:column;width:95%;}
        .score {float: right; font-weight: bold;}
        .round-details {border-bottom: 2px solid #ddd; border-right: 2px solid #ddd;}
        .team-bottom {width:75%; border-top: 2px solid #ddd;}
        .matchup {margin: 0; height: 60px; padding: 10px 0;}
        .round-1 {padding: 50px 0;}
        .round-2 {padding: 130px 0;}
        .round-3 {padding: 290px 0;}
        .team {padding: 0 5px;margin: 3px 0;height: 25px; line-height: 25px;white-space: nowrap; overflow: hidden;position: relative;}
        .round-details {text-align: center;}
        .result {border-left: 2px solid #ddd;}
        .result-data {padding: 20px;}
        .generate {padding: 20px; margin: 20px;}
    </style>
</head>
<body>
    <button class="generate" type="button">Generate Tournament Data</button>
    <div class="container"></div>
</body>
</html>

<script>
    $('.generate').on('click', function() {
        $.ajax({
            url: '/tournament',
            type: 'POST',
            success: function(res) {
                $('.container').html(res);
            },
            error: function() {
                alert('Unexpected Error!');
            }
        });
        return false;
    });
</script>

templates/tournament.html.twig
{% for division in tournament.divisions %}
    <table>
        <caption>{{ division.name }}</caption>
        <tr>
            <th>Teams</th>
            {% for team in division.teams %}
                <th>{{ team.name }}</th>
            {% endfor %}
            <th>Score</th>
        </tr>
        {% set line = 1 %}
        {% for team in division.teams %}
            <tr>
                <th>{{ team.name }}</th>
                {% set counter = 1 %}
                {% for result in team.groupResults %}
                    {% if counter == line %}
                        <td bgcolor="grey"></td>
                    {% endif %}

                    {% if counter < line %}
                        <td>{{ result.score|reverse }}</td>
                    {% else %}
                        <td>{{ result.score }}</td>
                    {% endif %}

                    {% set counter = counter + 1 %}
                {% endfor %}
                {% if line == division.teams|length %}
                    <td bgcolor="grey"></td>
                {% endif %}
                <td>{{ division.scores[team.getId()] }}</td>
            </tr>
            {% set line = line + 1 %}
        {% endfor %}
    </table>
{% endfor %}

<div class="result-data">
    <div class="split split-one">
        {% set counter = 0 %}
        {% for stage, stageData in playoffData %}
            <div class="round">
                <div class="round-details">Stage: {{ stage }}<br/></div>
                {% for result in stageData %}
                    <ul class="matchup round-{{ counter }}">
                        <li class="team team-top">{{ result.firstTeam }}<span class="score">{{ result.score }}</span></li>
                        <li class="team team-bottom">{{ result.secondTeam }}</li>
                    </ul>
                {% endfor %}
            </div>
            {% set counter = counter + 1 %}
        {% endfor %}

        <div class="round result">
            <div class="round-details">Result<br/></div>
            <ol>
                {% for result in results %}
                    <li>{{ result }}</li>
                {% endfor %}
            </ol>
        </div>
    </div>
</div>